### ISSUE TITLE
Add extra labels to servicemonitors

### ISSUE THREAD

**Issue by toggetit** [citrix/citrix-helm-charts#156]
Hello!
Can you add possibility to add custom extra labels to service monitor when exporter enabled?
This feature need for target autodiscovering when prometheus operator is using.
I can write simple patch to helm chart if needed

**Comment by ankits123** [comment]
Hi @toggetit thanks for the suggestion we will review this and get back.

**Comment by toggetit** [comment]
> Hi @toggetit thanks for the suggestion we will review this and get back.

I mean changes in citrix-ingress-controller.
There
https://github.com/citrix/citrix-helm-charts/blob/7014c386813c81ff8f1ccb8b25f445293c1e1b26/citrix-ingress-controller/templates/citrix-k8s-ingress.yaml#L226

**Comment by subashd** [comment]
hi @toggetit 
In recent release we have added the support for extra labels to service monitor. Please try the latest charts.
https://github.com/citrix/citrix-helm-charts/releases/tag/cic-v1.34.16
