### ISSUE TITLE
Duplicate Keys in cic_crds.yaml

### ISSUE THREAD

**Issue by BenB196** [citrix/citrix-helm-charts#26]
https://github.com/citrix/citrix-helm-charts/blob/master/citrix-ingress-controller/templates/cic_crds.yaml contains duplicate keys:

Resulting in the failure for it to be parsed into JSON and used within Helm

- https://github.com/citrix/citrix-helm-charts/blob/master/citrix-ingress-controller/templates/cic_crds.yaml#L389
- https://github.com/citrix/citrix-helm-charts/blob/master/citrix-ingress-controller/templates/cic_crds.yaml#L389

**Comment by priyankash-citrix** [comment]
@BenB196 Thanks for bringing this issue into our notice. We have fixed the same.
