### ISSUE TITLE
citrix-k8s-ingress-controller: Add ability to set arg --update-ingress-status

### ISSUE THREAD

**Issue by BenB196** [citrix/citrix-helm-charts#34]
The citrix-k8s-ingress-controller added --update-ingress-status in [1.8.19](https://github.com/citrix/citrix-k8s-ingress-controller/releases/tag/1.8.19), however, the citrix-ingress-controller helm chart does not provide a way to set this arg. It would be nice to have the ability to set this arg via helm, so it doesn't need to be manually added after the fact.

**Comment by priyankash-citrix** [comment]
Added support for this in 1.9.9 release.
