### ISSUE TITLE
Helm add ability to set tolerations

### ISSUE THREAD

**Issue by BenB196** [citrix/citrix-helm-charts#36]
Tolerations are useful for when you want to assign a pod to specific nodes. Currently it is not possible to set tolerations with these helm charts. This would be a nice addition as its extremely useful for when you want to pods to only run on specific nodes.

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by BenB196** [comment]
Any update on this enhancement? Would be a really good addition.

**Comment by subashd** [comment]
@BenB196 we will support this soon.

**Comment by eyenx** [comment]
Do you guys have a roadmap with which release comes what feature?

**Comment by dheerajng** [comment]
@eyenx Thanks for the follow-up. We would have support for this in next few weeks.

**Comment by priyankash-citrix** [comment]
@eyenx We have added support for providing toleration in Citrix Ingress controller and CPX with ingress controller helm charts in release 1.13.20. Please give it try and let us know in case of any query.

**Comment by eyenx** [comment]
Will update it on our dev env and give you some feedback
