### ISSUE TITLE
ReadOnly filesytem stops ssl certificates from being created/imported.

### ISSUE THREAD

**Issue by dunxiii** [citrix/citrix-helm-charts#6]
Hi

Seems that #3 introduced some problems for us, because of the read-only setting, now when certificates are being "created" in citrix-k8s-ingress-controller pod it throws the error.

`ERROR - [kubernetes.py:create_cert_data:2927] (MainThread) Could not create certificate file /tmp/foobar.crt: [Errno 30] Read-only file system: '/tmp/foobar.crt'`

This lead to no https conf is setup for the ingress. Is it working as intended and we are missing something?

Thanks

**Comment by Anganthier** [comment]
Hi,
+1

I locally added a emptyDir volume to the ingress controller pod template definition in the helm chart for /tmp. After that certificate creation does work.

Bye
David

**Comment by kumar-swamy** [comment]
This has been addressed in the latest build.
