### ISSUE TITLE
Update kubeVersion in Chart.yaml to fix issue with complex version strings

### ISSUE THREAD

**Issue by warrenrees** [citrix/citrix-helm-charts#96]
I attempted to install the helm chart for the ingress controller and it failed with the following error:

kubernetes@k8s-node-01:~$ helm install cic citrix/citrix-ingress-controller --set nsIP=10.0.0.137,license.accept=yes,adcCredentialSecret=nslogin
Error: chart requires kubeVersion: >=v1.16 < v1.22 which is incompatible with Kubernetes v1.21.3-3+6343a564e351b0

Can you please add -0 to the kubeVersion in order to allow this to be used with complex version strings?

For example, replace
kubeVersion: ">=v1.16 < v1.22"
with
kubeVersion: ">=v1.16-0 < v1.22-0"

Helm bug for reference: https://github.com/helm/helm/issues/9371

Thanks!

Warren

**Comment by priyankash-citrix** [comment]
The issue been fixed in the latest Chart.
Please try and let us know if anything else is required.
